#!/bin/sh

# This command optionall accepts the following arguments:
# -repository:	The docker repository
# -user:	The user under which the container is run (should match the one specified on build).
# -version:	The version of the image.
# 
# If you want to use these options you need to install `readopt` and `fitleropts`. 
# They can be found in the shell module and can be installed using `make helpers_install`.
#
S=`readopt -sandbox-id "$@" 2> /dev/null`
R=`readopt -repository "$@" 2> /dev/null`
U=`readopt -user "$@" 2> /dev/null`
V=`readopt -version "$@" 2> /dev/null`
A=`filteropts 4 -sandbox-id -user -version -repository "$@" 2> /dev/null`

REPOSITORY=${R:-"iocanel"}
USERNAME=${U:-"iocanel"}
VERSION=${V:-"latest"}
ARGS=${A:-"$@"}
TMP_DIR=`mktemp -d /tmp/tmp.spacemacs.XXXX`
SANDBOX_ID=${V:-"spacemacs"}

if [ ! -d ~/.sandbox/$SANDBOX_ID/.emacs.d ]; then mkdir -p ~/.sandbox/$SANDBOX_ID/.emacs.d; fi
if [ ! -d ~/.sandbox/$SANDBOX_ID/.spacemacs.d ]; then mkdir -p ~/.sandbox/$SANDBOX_ID/.spacemacs.d; fi

echo $A
echo $ARGS
xhost local:root
docker run -it \
           -w=/home/$USERNAME \
	   -v ~/Downloads:/home/$USERNAME/Downloads \
	   -v ~/Documents:/home/$USERNAME/Documents \
	   -v ~/workspace:/home/$USERNAME/workspace \
	   -v ~/.sandbox/$SANDBOX_ID/.emacs.d:/home/$USERNAME/.emacs.d \
	   -v ~/.sandbox/$SANDBOX_ID/.spacemacs.d:/home/$USERNAME/.spacemacs.d \
	   -v ~/.sandbox/$SANDBOX_ID:/home/$USERNAME/.sandbox/$SANDBOX_ID \
	   -v /tmp/.X11-unix:/tmp/.X11-unix \
           -e DISPLAY=$DISPLAY \
	   -e XDG_CONFIG_HOME=/home/$USERNAME/.sandbox/$SANDBOX_ID/.config \
           -e XDG_CACHE_HOME=/home/$USERNAME/.sandbox/$SANDBOX_ID/.cache \
           -e XDG_DATA_HOME=/home/$USERNAME/.sandbox/$SANDBOX_ID/.local/share \
           --cpuset-cpus 0 \
	   --net=host \
	   -v /dev/shm/:/dev/shm/ \
           -v /var/run:/var/run/ \
           --privileged \
           $REPOSITORY/spacemacs:$VERSION $ARGS
