#!/bin/sh

# This command optionall accepts the following arguments:
# -repository:	The docker repository
# -user:	The user under which the container is run (should match the one specified on build).
# -version:	The version of the image.
# 
# If you want to use these options you need to install `readopt` and `fitleropts`. 
# They can be found in the shell module and can be installed using `make helpers_install`.
#
R=`readopt -repository "$@" 2> /dev/null`
U=`readopt -user "$@" 2> /dev/null`
V=`readopt -version "$@" 2> /dev/null`
W=`readopt -wiki-dir "$@" 2> /dev/null`
ARGS=`filteropts 4 -user -version -repository -wiki-dir "$@" 2> /dev/null`
REPOSITORY=${R:-"iocanel"}
USERNAME=${U:-"iocanel"}
VERSION=${V:-"latest"}
WIKI_DIR=${W:-"$HOME/wiki"}

xhost local:root
docker run \
       -v $WIKI_DIR:/home/$USERNAME/wiki \
       --net=host \
       --privileged \
       $REPOSITORY/mdwiki:$VERSION /wiki $ARGS
