#!/bin/sh

# This command optionall accepts the following arguments:
# -repository:	The docker repository
# -user:	The user under which the container is run (should match the one specified on build).
# -version:	The version of the image.
# 
# If you want to use these options you need to install `readopt` and `fitleropts`. 
# They can be found in the shell module and can be installed using `make helpers_install`.
#
R=`readopt -repository "$@" 2> /dev/null`
U=`readopt -user "$@" 2> /dev/null`
V=`readopt -version "$@" 2> /dev/null`
W=`readopt -www-data "$@" 2> /dev/null`
ARGS=`filteropts 4 -user -version -repository -www-data "$@" 2> /dev/null`
REPOSITORY=${R:-"iocanel"}
USERNAME=${U:-"iocanel"}
VERSION=${V:-"latest"}
WWW_DATA=${W:-"$HOME/www"}

xhost local:root
docker run \
       -v $WWW_DATA:/www \
       --net=host \
       --privileged \
       $REPOSITORY/http-server:$VERSION /www $ARGS
