#!/bin/sh

# This command optionall accepts the following arguments:
# -repository:	The docker repository
# -user:	The user under which the container is run (should match the one specified on build).
# -version:	The version of the image.
# 
# If you want to use these options you need to install `readopt` and `fitleropts`. 
# They can be found in the shell module and can be installed using `make helpers_install`.
#
S=`readopt -sandbox-id "$@" 2> /dev/null`
R=`readopt -repository "$@" 2> /dev/null`
U=`readopt -user "$@" 2> /dev/null`
V=`readopt -version "$@" 2> /dev/null`
ARGS=`filteropts 4 -sandbox-id -user -version -repository "$@" 2> /dev/null`

REPOSITORY=${R:-"iocanel"}
USERNAME=${U:-"iocanel"}
VERSION=${V:-"latest"}
SANDBOX_ID=${S:-"doom"}

if [ ! -d ~/.sandbox/$SANDBOX_ID/.emacs.d ]; then mkdir -p ~/.sandbox/$SANDBOX_ID/.emacs.d; fi
if [ ! -d ~/.sandbox/$SANDBOX_ID/.doom.d ]; then mkdir -p ~/.sandbox/$SANDBOX_ID/.doom.d; fi

xhost local:root
docker run \
	   -v ~/Downloads:/home/$USERNAME/Downloads \
	   -v ~/Documents:/home/$USERNAME/Documents \
	   -v ~/workspace:/home/$USERNAME/workspace \
	   -v ~/.sandbox/$SANDBOX_ID/.emacs.d:/home/$USERNAME/.emacs.d \
	   -v ~/.sandbox/$SANDBOX_ID/.doom.d:/home/$USERNAME/.doom.d \
	   -v ~/.sandbox/$SANDBOX_ID:/home/$USERNAME/.sandbox/$SANDBOX_ID \
	   -v /tmp/.X11-unix:/tmp/.X11-unix \
	   -v /dev/shm/:/dev/shm/ \
           -v /var/run:/var/run/ \
           -e DISPLAY=$DISPLAY \
           --net=host \
           --cpuset-cpus 0 \
           --privileged \
           $REPOSITORY/doom:$VERSION $ARGS
