#!/bin/sh

# This command optionall accepts the following arguments:
# -repository:	The docker repository
# -user:	The user under which the container is run (should match the one specified on build).
# -version:	The version of the image.
# 
# If you want to use these options you need to install `readopt` and `fitleropts`.
# They can be found in the shell module and can be installed using `make helpers_install`.
#
S=`readopt -sandbox-id "$@" 2> /dev/null`
R=`readopt -repository "$@" 2> /dev/null`
U=`readopt -user "$@" 2> /dev/null`
V=`readopt -version "$@" 2> /dev/null`
ARGS=`filteropts 3 -user -version -repository "$@" 2> /dev/null`

REPOSITORY=${R:-"iocanel"}
USERNAME=${U:-"iocanel"}
VERSION=${V:-"latest"}
SANDBOX_ID=${S:-"doom"}

docker run -it \
          -w=/home/$USERNAME \
          -v ~/Downloads:/home/$USERNAME/Downloads \
          -v ~/Documents:/home/$USERNAME/Documents \
          -v ~/workspace:/home/$USERNAME/workspace \
          -v ~/.sandbox/$SANDBOX_ID/.emacs.d:/home/$USERNAME/.emacs.d \
          -v ~/.sandbox/$SANDBOX_ID/.doom.d:/home/$USERNAME/.doom.d \
          -v ~/.sandbox/$SANDBOX_ID:/home/$USERNAME/.sandbox/$SANDBOX_ID \
          -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
          -e DISPLAY=$DISPLAY \
	   --entrypoint adduser-and-run.sh  $REPOSITORY/doom:$VERSION /bin/sh

